### ISSUE TITLE
L10n of 4.2.x documentation - CJK PDFs for the Client Configuration Guide - missing content. Table corruption due to conditional text settings.

### ISSUE THREAD

**Issue by ptinley-vt** [uyuni-project/uyuni-docs#1303]
**Description:** Table 1, on page 2, is a 22 row, 4 column table in the English book. However, in all 3 localised languages (CJK) the table is truncated to just 2 rows.  
The header row in EN is:
Operating System | Architecture | Traditional Clients | Salt Clients
The header row in the targets contain content from the normal body of the table which has been shifted up into the header row.
x86-64、aarch64 | x86-64、aarch64 | x86-64 x | 86-64
This is caused by different conditional text settings (incorrect 'ifeval' statement) in the file modules/client-configuration/pages/supported-features.adoc
![client-configuration_table1_conditional_text](https://user-images.githubusercontent.com/68334239/143288926-dd3a20a3-5066-46f8-b095-744c934f1346.PNG)

English on the left -- localised Japanese on the right.

See here for currently published: 
https://documentation.suse.com/suma/4.2/ja/pdf/suse_manager_client-configuration_guide.pdf
Page 6 of PDF (folio 2).
Compare with English:
https://documentation.suse.com/suma/4.2/en/pdf/suse_manager_client-configuration_guide.pdf
Page 6 of PDF (folio 2).

**Comment by jcayouette** [comment]
Thank you! @ptinley-vt

**Comment by jcayouette** [comment]
Fixed by created two tables with one ifeval for each product.

**Comment by ptinley-vt** [comment]
Hi Joseph.

This is still an issue in the CJK Client Configuration Guides (4.2.7). 
Was also an issue in 4.3 rc1.
It was OK in 4.2.5 and 4.2.6.

**Please reopen.**

![image](https://user-images.githubusercontent.com/68334239/174789129-20d0d19f-751b-4d6b-83c5-7fd2952af842.png)

The localised modules/client-configuration/pages/supported-features.adoc file has and ifeval appear where there is not one in the EN version, in the second version of the table tagged with  'ifeval::[{suma-content} == true]' (line 163 in the EN file.)

![image](https://user-images.githubusercontent.com/68334239/174790089-9c327bcc-c290-4e84-b05d-2ace1d0bdcd0.png)

The table-end closes differently too.

![image](https://user-images.githubusercontent.com/68334239/174790675-26c2ab6a-3eb0-4673-9272-48b64e51a9d8.png)

Regards,
Patrick
